### ISSUE TITLE
Nethereum Package -> unsafe code

### ISSUE THREAD

**Issue by Gizmotronn** [ethereum-boilerplate/ethereum-unity-boilerplate#40] opened 2022-02-10 11:41 UTC
Unity version: Unity 2021 (latest)
Release of `ethereum-unity-boilerplate`: [1.0.4](https://github.com/ethereum-boilerplate/ethereum-unity-boilerplate/releases/tag/v1.0.4)

Error: Around 11 unsafe code errors:
`Assets/MoralisWeb3ApiSdk/Nethereum/Nethereum.KeyStore/Crypto/SCrypt.cs(290,36): error CS0227: Unsafe code may only appear if compiling with /unsafe. Enable "Allow 'unsafe' code" in Player Settings to fix this error.`

This can be fixed by going into "Player Settings" and allowing "unsafe code", however I didn't notice this on previous releases and this is not a good solution for a production environment.

**Comment by xactant** [comment] 2022-02-10 11:59
HI this is mentioned in the setup steps of the README

Due to code in Nethereum you need to set the flag for "Allow Unsafe Code" in Player Setting.

**Comment by xactant** [comment] 2022-02-10 12:11
No, it is not a bug. Nethereum uses a set of unsafe code blocks (see the SCrypt.cs file) that are required for Nethereum to work properly.

**Comment by xactant** [comment] 2022-02-28 15:34
Closing as this is not a bug but a known condition in Nethereum with a documented work around.

**Closed by xactant** 2022-02-28 15:34 UTC
